"""
Build Orchestrator — coordinates the full Builder → Security pipeline.

After architecture approval, this runs as a background asyncio task:
1. Create project folder
2. Create base structure
3. Create README.md
4. Create project manifest
5. Execute coding tasks sequentially
Each step: Builder executes → Security reviews → proceed or retry.

Task State Machine:
  Pending → Assigned → Running → (Completed | Failed)
  Security: Pending → Reviewing → (Approved | Rejected)
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from datetime import datetime

from app.core.event_bus import event_bus
from app.schemas import BuildProgress, BuildReport, Event, TaskCreate, TaskUpdate
from app.services.time_service import now_label

logger = logging.getLogger("build_orchestrator")

MAX_RETRIES = 2
MAX_QA_RETRIES = 3

# Lazy import to avoid circular dependencies
def _get_job_manager():
    from app.services.job_manager import job_manager
    return job_manager


class BuildOrchestrator:
    """Manages end-to-end build pipelines."""

    def __init__(self):
        self.active_builds: dict[str, asyncio.Task] = {}
        self.build_states: dict[str, dict] = {}

    async def _qa_compile_check(self, workspace_path: str, task: Any) -> tuple[bool, str | None]:
        """
        Run a lightweight QA check on the files generated by this task.
        Checks if file is not empty, and performs basic code sanity checks.
        """
        if not getattr(task, "output_files", None):
            return True, None
            
        native_path = workspace_path.replace("/", os.sep)
        
        for fpath in task.output_files:
            abs_fpath = os.path.join(native_path, fpath.replace("/", os.sep))
            if not os.path.exists(abs_fpath):
                return False, f"Output file missing: {fpath}"
                
            try:
                size = os.path.getsize(abs_fpath)
                if size < 10:
                    return False, f"Output file is suspiciously empty (<10 bytes): {fpath}"
                    
                if fpath.endswith((".js", ".jsx", ".css")):
                    with open(abs_fpath, "r", encoding="utf-8") as f:
                        content = f.read()
                    
                    if "```" in content:
                        return False, f"Output file contains markdown code fences: {fpath}"
                        
                if fpath.endswith((".js", ".jsx")):
                    # Basic JS/JSX sanity check
                    if "return" not in content and "=>" not in content and "export" not in content:
                        return False, f"Output file does not look like valid JavaScript/React code (missing return/export): {fpath}"
            except Exception as e:
                logger.warning(f"QA check encountered an error verifying {fpath}: {e}")
                
        return True, None

    async def start_pipeline(self, workspace_id: str, architecture: dict | None = None) -> None:
        """Entry point: start building a workspace.

        Creates a Job via job_manager so the build persists independently
        of UI state — the user can navigate away, refresh, or close the
        browser and the build continues.
        """
        if workspace_id in self.active_builds:
            return  # Already building

        self.build_states[workspace_id] = {
            "status": "Building",
            "started_at": datetime.now(),
            "last_activity": now_label(),
            "architecture": architecture,
        }

        # Create a tracked Job instead of a raw asyncio task
        jm = _get_job_manager()
        job = jm.create_job(
            agent="Builder",
            workspace_id=workspace_id,
        )
        self.build_states[workspace_id]["job_id"] = job.job_id

        # Start via job manager — wraps our coroutine with lifecycle tracking
        await jm.start_job(
            job.job_id,
            self._run_pipeline_job,
            workspace_id,
            architecture,
        )

        # Keep reference for cancellation
        task = jm._tasks.get(job.job_id)
        if task:
            self.active_builds[workspace_id] = task

    def get_architecture(self, workspace_id: str) -> dict | None:
        """Retrieve stored architecture for a workspace build."""
        state = self.build_states.get(workspace_id, {})
        return state.get("architecture")

    async def _run_pipeline_job(self, job_id: str, workspace_id: str, architecture: dict | None) -> None:
        """Job-aware wrapper for the build pipeline."""
        await self._run_pipeline(workspace_id, architecture, job_id=job_id)

    async def _run_pipeline(self, workspace_id: str, architecture: dict | None, *, job_id: str | None = None) -> None:
        """Run the full build pipeline sequentially."""
        from app.services.builder_service import builder_service
        from app.services.security_service import security_service
        from app.services.task_service import task_service
        from app.services.workspace_service import workspace_service
        from app.services.agent_service import agent_service
        from app.services.execution_logger import execution_logger
        from app.services.spec_engine import spec_engine
        from app.services.evaluation_engine import evaluation_engine

        try:
            # Update agents
            agent_service.update("builder-agent", status="Running", current_task="Starting build pipeline")
            agent_service.update("security-agent", status="Running", current_task="Monitoring review queue")

            await event_bus.publish(Event(
                type="BUILD_STARTED",
                source="Build Orchestrator",
                message=f"Build pipeline started for workspace {workspace_id}",
                severity="success",
                payload={"workspace_id": workspace_id},
            ))

            workspace = workspace_service.get(workspace_id)
            workspace_service.update_build_status(workspace_id, "Building", "Builder Agent", "Starting...")

            # Log pipeline start
            execution_logger.log(workspace.path, "Build Orchestrator", "PIPELINE_STARTED", details=f"Building {workspace.name}")

            # ── Create foundation tasks if they don't exist ───────────────
            existing_tasks = task_service.list_by_workspace(workspace_id)
            existing_titles = {t.title.lower() for t in existing_tasks}

            foundation_tasks = [
                ("Create Project Folder", "Create the project root directory on disk.", "Critical", "Builder Agent"),
                ("Create Base Structure", "Create frontend/, backend/, docs/, .agentos/ directories.", "Critical", "Builder Agent"),
                ("Create README.md", "Generate project README with name, description, tech stack, and metadata.", "High", "Builder Agent"),
                ("Create Project Manifest", "Generate .agentos/project.json with full project metadata.", "High", "Builder Agent"),
            ]

            for title, desc, priority, agent in foundation_tasks:
                if title.lower() not in existing_titles:
                    task_service.create(TaskCreate(
                        title=title,
                        description=desc,
                        assigned_agent=agent,
                        priority=priority,
                        workspace_id=workspace_id,
                    ))

            # Ensure all existing tasks belong to this workspace
            for task in existing_tasks:
                if not task.workspace_id:
                    task_service.update(TaskUpdate(id=task.id, workspace_id=workspace_id))

            # Recalculate progress
            workspace_service.recalculate_progress(workspace_id)

            # ── Process tasks one by one ──────────────────────────────────
            while True:
                next_task = task_service.next_pending_task(workspace_id)
                if not next_task:
                    break  # All tasks done

                # ── P4: Sync current task on workspace ────────────────────
                workspace_service.update_build_status(
                    workspace_id, "Building", "Builder Agent", next_task.title
                )

                # Determine which agent should handle this task
                is_builder_task = next_task.assigned_agent in ("Builder Agent", "Head Agent") or \
                    self._is_build_task(next_task.title)
                is_security_task = next_task.assigned_agent == "Security Agent"

                if is_builder_task:
                    # Builder executes
                    agent_service.update("builder-agent", status="Running", current_task=next_task.title)
                    workspace_service.update_build_status(workspace_id, "Building", "Builder Agent", next_task.title)

                    build_result = await builder_service.execute_task(
                        next_task.id, workspace_id, architecture=architecture
                    )

                    if build_result["status"] == "error":
                        logger.error(f"Builder failed on task {next_task.id}: {build_result.get('error')}")
                        # Explicitly mark task as failed
                        task_service.update(TaskUpdate(
                            id=next_task.id,
                            status="Failed",
                            security_notes=f"Builder error: {build_result.get('error', 'Unknown')}",
                        ))

                        execution_logger.log(
                            workspace.path, "Build Orchestrator", "TASK_FAILED",
                            next_task.id, build_result.get("error", "Unknown")
                        )

                        await event_bus.publish(Event(
                            type="BUILD_TASK_FAILED",
                            source="Build Orchestrator",
                            message=f"Task failed: {next_task.title}",
                            severity="error",
                            payload={"task_id": next_task.id, "workspace_id": workspace_id},
                        ))

                        await asyncio.sleep(0.5)
                        # Recalculate and continue to next task
                        workspace_service.recalculate_progress(workspace_id)
                        continue

                    # Security reviews builder output
                    agent_service.update("security-agent", status="Running", current_task=f"Reviewing: {next_task.title}")
                    workspace_service.update_build_status(workspace_id, "Reviewing", "Security Agent", next_task.title)

                    review_result = await security_service.review_task(next_task.id, workspace_id)

                    if not review_result.approved:
                        # Retry logic
                        retry_count = self.build_states.get(workspace_id, {}).get(f"retry_{next_task.id}", 0)
                        if retry_count < MAX_RETRIES:
                            self.build_states[workspace_id][f"retry_{next_task.id}"] = retry_count + 1
                            # Reset task to Pending for retry
                            task_service.update(TaskUpdate(
                                id=next_task.id,
                                status="Pending",
                                security_status="Pending",
                                security_notes=f"Retry {retry_count + 1}/{MAX_RETRIES}: {review_result.notes}",
                            ))

                            await event_bus.publish(Event(
                                type="BUILD_TASK_RETRY",
                                source="Build Orchestrator",
                                message=f"Retrying task: {next_task.title} (attempt {retry_count + 2})",
                                severity="warning",
                                payload={"task_id": next_task.id, "workspace_id": workspace_id},
                            ))
                            continue
                        else:
                            # Max retries reached — log and move on
                            execution_logger.log(
                                workspace.path, "Build Orchestrator", "TASK_MAX_RETRIES",
                                next_task.id, f"Skipped after {MAX_RETRIES} retries"
                            )
                            await event_bus.publish(Event(
                                type="BUILD_TASK_SKIPPED",
                                source="Build Orchestrator",
                                message=f"Skipping task after {MAX_RETRIES} retries: {next_task.title}",
                                severity="warning",
                                payload={"task_id": next_task.id, "workspace_id": workspace_id},
                            ))
                            continue

                    # ── QA Compile Check (Only if Security Approved) ──────────────
                    qa_passed, qa_error = await self._qa_compile_check(workspace.path, next_task)
                    
                    if not qa_passed:
                        qa_retry_count = self.build_states.get(workspace_id, {}).get(f"qa_retry_{next_task.id}", 0)
                        if qa_retry_count < MAX_QA_RETRIES:
                            self.build_states[workspace_id][f"qa_retry_{next_task.id}"] = qa_retry_count + 1
                            
                            # Append error to description so Builder sees it on next try
                            new_desc = next_task.description
                            if "QA FAIL TRACE:" not in new_desc:
                                new_desc += f"\n\nQA FAIL TRACE:\n{qa_error}"
                            else:
                                new_desc = new_desc.split("QA FAIL TRACE:")[0] + f"QA FAIL TRACE:\n{qa_error}"
                                
                            task_service.update(TaskUpdate(
                                id=next_task.id,
                                status="Pending",
                                security_status="Pending",
                                description=new_desc,
                                security_notes=f"QA check failed (Attempt {qa_retry_count + 1}/{MAX_QA_RETRIES}): {qa_error}"
                            ))
                            
                            await event_bus.publish(Event(
                                type="BUILD_TASK_RETRY",
                                source="Build Orchestrator",
                                message=f"QA failed, retrying task: {next_task.title}",
                                severity="warning",
                                payload={"task_id": next_task.id, "workspace_id": workspace_id},
                            ))
                            continue
                        else:
                            # Max QA retries reached — fail the task permanently
                            task_service.update(TaskUpdate(
                                id=next_task.id,
                                status="Failed",
                                security_notes=f"QA failed permanently after {MAX_QA_RETRIES} retries: {qa_error}"
                            ))
                            
                            execution_logger.log(
                                workspace.path, "Build Orchestrator", "TASK_FAILED",
                                next_task.id, f"QA failed permanently: {qa_error}"
                            )
                            continue

                elif is_security_task:
                    # Security-only tasks (review, testing, etc.)
                    agent_service.update("security-agent", status="Running", current_task=next_task.title)
                    workspace_service.update_build_status(workspace_id, "Reviewing", "Security Agent", next_task.title)

                    # Mark as running
                    task_service.update(TaskUpdate(id=next_task.id, status="Running"))

                    review_result = await security_service.review_task(next_task.id, workspace_id)

                    task_service.update(TaskUpdate(
                        id=next_task.id,
                        status="Completed",
                    ))

                    execution_logger.log(
                        workspace.path, "Security Agent", "TASK_COMPLETED",
                        next_task.id, next_task.title
                    )

                else:
                    # Head Agent planning tasks — mark as completed (planning is done)
                    task_service.update(TaskUpdate(
                        id=next_task.id,
                        status="Completed",
                    ))

                    await event_bus.publish(Event(
                        type="BUILD_TASK_COMPLETED",
                        source="Head Agent",
                        message=f"Planning task completed: {next_task.title}",
                        severity="success",
                        payload={"task_id": next_task.id, "workspace_id": workspace_id, "title": next_task.title},
                    ))

                # Update progress after each task
                workspace = workspace_service.recalculate_progress(workspace_id)
                self.build_states[workspace_id]["last_activity"] = now_label()

                # Update job progress
                if job_id:
                    _get_job_manager().update_progress(
                        job_id,
                        progress=workspace.progress,
                        message=f"Building: {workspace.current_task_title or 'processing'}",
                    )

                await event_bus.publish(Event(
                    type="BUILD_PROGRESS_UPDATED",
                    source="Build Orchestrator",
                    message=f"Build progress: {workspace.progress}%",
                    severity="info",
                    payload={
                        "workspace_id": workspace_id,
                        "progress": workspace.progress,
                        "eta_minutes": workspace.estimated_completion_minutes,
                    },
                ))

                # Small delay between tasks for UI readability
                await asyncio.sleep(0.5)

            # ── Sprint 4: Autonomous Improvement Loop ──────────────────────
            # Only run the loop if there were no fatal pipeline failures so far.
            failed_count = task_service.count_failed(workspace_id)
            completed_count = task_service.count_completed(workspace_id)
            
            final_status = "Completed"
            spec = spec_engine.read_spec(workspace.path) or {}

            if failed_count == 0 or completed_count > 0:
                MAX_IMPROVEMENT_CYCLES = 3
                
                for cycle in range(MAX_IMPROVEMENT_CYCLES):
                    # 1. Evaluate the project
                    evaluation = evaluation_engine.evaluate(workspace.path, spec)
                    
                    # 2. Check new completion rules
                    if evaluation["passed"]:
                        logger.info(f"Workspace {workspace_id} passed evaluation with score {evaluation['overall_score']}")
                        break  # Done!
                        
                    # 3. Detect gaps
                    gaps = evaluation_engine.detect_gaps(spec, evaluation)
                    if not gaps:
                        logger.info(f"Workspace {workspace_id} has low score but no actionable gaps found.")
                        break  # Nothing more we can do autonomously
                        
                    # 4. Generate improvement tasks
                    logger.info(f"Improvement cycle {cycle+1}/{MAX_IMPROVEMENT_CYCLES}: Generating {len(gaps)} tasks")
                    new_tasks = evaluation_engine.generate_improvement_tasks(gaps, spec, workspace_id)
                    
                    if not new_tasks:
                        break
                        
                    for task_create in new_tasks:
                        task_service.create(task_create)
                        
                    workspace_service.recalculate_progress(workspace_id)
                    
                    # Log improvement loop start
                    execution_logger.log(
                        workspace.path, "Build Orchestrator", "IMPROVEMENT_CYCLE_STARTED", 
                        details=f"Cycle {cycle+1}: Score {evaluation['overall_score']}, adding {len(new_tasks)} tasks"
                    )
                    
                    # 5. Execute the new tasks (jump back to the task processor)
                    while True:
                        next_task = task_service.next_pending_task(workspace_id)
                        if not next_task:
                            break
                            
                        workspace_service.update_build_status(
                            workspace_id, "Building", "Builder Agent", next_task.title
                        )
                        
                        agent_service.update("builder-agent", status="Running", current_task=next_task.title)
                        build_result = await builder_service.execute_task(
                            next_task.id, workspace_id, architecture=architecture
                        )
                        
                        if build_result["status"] == "error":
                            task_service.update(TaskUpdate(id=next_task.id, status="Failed"))
                            workspace_service.recalculate_progress(workspace_id)
                            continue
                            
                        task_service.update(TaskUpdate(id=next_task.id, status="Completed"))
                        workspace_service.recalculate_progress(workspace_id)
                        await asyncio.sleep(0.5)

            # ── P6: Pipeline complete — full completion logic ─────────────
            failed_count = task_service.count_failed(workspace_id)
            completed_count = task_service.count_completed(workspace_id)
            total_count = task_service.count_total(workspace_id)

            # Determine final status
            if failed_count > 0 and completed_count == 0:
                final_status = "Failed"

            # P6: Set all completion fields explicitly
            completion_time = now_label()
            workspace_service.update(
                workspace_id,
                status=final_status,
                progress=int((completed_count / total_count) * 100) if total_count > 0 else 100,
                current_agent=None,
                current_task_title=None,
                estimated_completion_minutes=0,
                completed_at=completion_time,
            )

            agent_service.update("builder-agent", status="Idle", current_task="Build complete")
            agent_service.update("security-agent", status="Idle", current_task="Build complete")

            # Mark job as completed
            if job_id:
                _get_job_manager().update_progress(job_id, progress=100, message=f"Build {final_status.lower()}")

            execution_logger.log(workspace.path, "Build Orchestrator", "PIPELINE_COMPLETED",
                                 details=f"Status: {final_status}, Completed: {completed_count}, Failed: {failed_count}")

            # ── P10: Generate build report ────────────────────────────────
            workspace = workspace_service.get(workspace_id)
            report = self._generate_build_report(workspace_id, workspace)
            workspace_service.store_build_report(workspace_id, report)

            # ── P9: Archive the workspace ─────────────────────────────────
            workspace_service.archive_workspace(workspace)

            # ── Publish BUILD_COMPLETED event ─────────────────────────────
            await event_bus.publish(Event(
                type="BUILD_COMPLETED",
                source="Build Orchestrator",
                message=f"Build {final_status.lower()} for {workspace.project_name}",
                severity="success" if final_status == "Completed" else "warning",
                payload={
                    "workspace_id": workspace_id,
                    "status": final_status,
                    "report": report,
                },
            ))

            self.build_states[workspace_id]["status"] = final_status

        except asyncio.CancelledError:
            workspace_service.update(
                workspace_id,
                status="Failed",
                current_agent=None,
                current_task_title=None,
            )
            agent_service.update("builder-agent", status="Paused", current_task="Build cancelled")
            agent_service.update("security-agent", status="Idle", current_task="Monitoring review queue")

            await event_bus.publish(Event(
                type="BUILD_FAILED",
                source="Build Orchestrator",
                message=f"Build cancelled for workspace {workspace_id}",
                severity="error",
                payload={"workspace_id": workspace_id},
            ))

        except Exception as e:
            logger.exception(f"Build pipeline failed for {workspace_id}")
            workspace_service.update(
                workspace_id,
                status="Failed",
                current_agent=None,
                current_task_title=None,
            )
            agent_service.update("builder-agent", status="Paused", current_task=f"Error: {str(e)[:80]}")
            agent_service.update("security-agent", status="Idle", current_task="Monitoring review queue")

            try:
                workspace = workspace_service.get(workspace_id)
                execution_logger.log(workspace.path, "Build Orchestrator", "PIPELINE_FAILED", details=str(e))
            except Exception:
                pass

            await event_bus.publish(Event(
                type="BUILD_FAILED",
                source="Build Orchestrator",
                message=f"Build failed: {str(e)[:120]}",
                severity="error",
                payload={"workspace_id": workspace_id, "error": str(e)},
            ))

        finally:
            self.active_builds.pop(workspace_id, None)

    # ── Build Report Generation (P10) ─────────────────────────────────────

    def _generate_build_report(self, workspace_id: str, workspace) -> dict:
        """Generate a build report and write to .agentos/build_report.json."""
        from app.services.task_service import task_service
        from app.services.spec_engine import spec_engine
        from app.services.evaluation_engine import evaluation_engine

        completed = task_service.count_completed(workspace_id)
        failed = task_service.count_failed(workspace_id)
        total = task_service.count_total(workspace_id)
        approved = task_service.count_security_approved(workspace_id)
        rejected = task_service.count_security_rejected(workspace_id)
        files_created = task_service.count_output_files(workspace_id)

        # Calculate build duration
        build_state = self.build_states.get(workspace_id, {})
        started_at = build_state.get("started_at")
        duration_seconds = 0
        duration_display = "0s"
        if started_at:
            delta = datetime.now() - started_at
            duration_seconds = delta.total_seconds()
            minutes = int(duration_seconds // 60)
            seconds = int(duration_seconds % 60)
            if minutes > 0:
                duration_display = f"{minutes}m {seconds}s"
            else:
                duration_display = f"{seconds}s"

        # Sprint 4: Real evaluation scoring
        spec = spec_engine.read_spec(workspace.path) or {}
        evaluation = evaluation_engine.evaluate(workspace.path, spec)
        
        # Pull basic stats from the evaluation
        pages_created = 0
        components_created = 0
        assets_created = 0
        
        frontend_src = os.path.join(workspace.path.replace("/", os.sep), "frontend", "src")
        if os.path.exists(frontend_src):
            for root_dir, dirs, files in os.walk(frontend_src):
                if "pages" in root_dir.lower():
                    pages_created += len([f for f in files if f.endswith((".js", ".jsx", ".ts", ".tsx"))])
                elif "components" in root_dir.lower():
                    components_created += len([f for f in files if f.endswith((".js", ".jsx", ".ts", ".tsx"))])
                elif "assets" in root_dir.lower():
                    assets_created += len(files)

        report = {
            "workspace_id": workspace_id,
            "project_name": workspace.project_name,
            "location": workspace.path,
            "files_created": files_created,
            "pages_created": pages_created,
            "components_created": components_created,
            "assets_created": assets_created,
            "tasks_completed": completed,
            "tasks_failed": failed,
            "tasks_total": total,
            "security_reviews_approved": approved,
            "security_reviews_rejected": rejected,
            "build_duration_seconds": round(duration_seconds, 2),
            "build_duration_display": duration_display,
            "build_quality_score": evaluation["overall_score"],
            "dimension_scores": evaluation.get("dimension_scores", {}),
            "missing_features": evaluation.get("missing_features", []),
            "quality_passed": evaluation.get("passed", False),
            "warnings": [gap.get("detail", "Gap found") for gap in evaluation.get("gaps", [])],
            "status": workspace.status,
            "generated_at": now_label(),
        }

        # Write to disk
        try:
            report_path = os.path.join(
                workspace.path.replace("/", os.sep), ".agentos", "build_report.json"
            )
            os.makedirs(os.path.dirname(report_path), exist_ok=True)
            with open(report_path, "w", encoding="utf-8") as f:
                json.dump(report, f, indent=2, default=str)
        except OSError as e:
            logger.warning(f"Could not write build report: {e}")

        return report

    # ── Helpers ───────────────────────────────────────────────────────────

    def _is_build_task(self, title: str) -> bool:
        """Check if a task title indicates a build/implementation task."""
        build_keywords = ["build", "create", "implement", "frontend", "backend",
                          "component", "feature", "setup", "scaffold", "shell",
                          "readme", "manifest", "folder", "structure",
                          # Sprint M1: atomic task keywords
                          "model", "schema", "endpoint", "config", "variable",
                          "theme", "context", "route", "routing", "responsive",
                          "layout", "style", "navbar", "footer", "hero", "card",
                          "form", "modal", "service", "crud", "migration", "seed",
                          "middleware", "handler", "controller", "client", "axios",
                          "fetch", "state", "loading", "error", "animation",
                          "transition", "seo", "meta", "optimization", "menu",
                          "section", "gallery", "catalog", "dashboard", "chart",
                          "filter", "search", "toggle", "wrapper", "provider"]
        title_lower = title.lower()
        return any(kw in title_lower for kw in build_keywords)

    # ── Query Methods ─────────────────────────────────────────────────────

    def get_build_progress(self, workspace_id: str) -> BuildProgress:
        """Get current build progress for a workspace."""
        from app.services.task_service import task_service
        from app.services.workspace_service import workspace_service

        try:
            workspace = workspace_service.get(workspace_id)
        except Exception:
            return BuildProgress(workspace_id=workspace_id)

        total = task_service.count_total(workspace_id)
        completed = task_service.count_completed(workspace_id)
        progress = int((completed / total) * 100) if total > 0 else 0

        state = self.build_states.get(workspace_id, {})

        return BuildProgress(
            workspace_id=workspace_id,
            total_tasks=total,
            completed_tasks=completed,
            progress_percent=progress,
            estimated_minutes_remaining=workspace.estimated_completion_minutes,
            current_agent=workspace.current_agent,
            current_task_title=workspace.current_task_title,
            status=workspace.status,
            last_activity=state.get("last_activity"),
        )

    def cancel_build(self, workspace_id: str) -> bool:
        """Cancel an active build."""
        task = self.active_builds.get(workspace_id)
        if task and not task.done():
            task.cancel()
            return True
        return False

    def is_building(self, workspace_id: str) -> bool:
        task = self.active_builds.get(workspace_id)
        return task is not None and not task.done()


# ── Singleton ─────────────────────────────────────────────────────────────

build_orchestrator = BuildOrchestrator()
